In [1]:
import gym

In [ ]:
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print "Episode finished after {} timesteps".format(t+1)
            break

In [ ]:
env = gym.make('CartPole-v0')
highscore = 0
for i in range(20):    # run 20 episodes
    observation = env.reset()
    points = 0    # keep track of reward each episode
    while True:
        env.render()
        action = 1 if observation[2] > 0 else 0    # if angle is positive, move right; if angle is negative, move left
        observation, reward, done, info = env.step(action)
        points += reward
        if done:
            if points > highscore:
                highscore = points
                break

In [ ]:
env = gym.make('SpaceInvaders-v0')
env.reset()
for _ in range(1000):
    env.render()
    action = env.action_space.sample()
    env.step(action)

# Q-Table Learning

In [2]:
import gym
import numpy as np

In [3]:
env = gym.make('FrozenLake-v0')

[2017-07-08 22:52:29,620] Making new env: FrozenLake-v0


In [9]:
# Initialize table with all zeros
Q = np.zeros([env.observation_space.n, env.action_space.n])
# Set learning parameters
alpha = .8    # learning rate
gamma = .95   # discount factor
num_episodes = 2000
# Create lists to contain total rewards and steps per episode
rewardsList = []
for i in range(num_episodes):
    s = env.reset()
    rAll = 0
    done = False
    j = 0
    while j < 99:
        j+= 1
        # Greedy action pick from Q table
        a = np.argmax(Q[s, :] + np.random.randn(1, env.action_space.n)*1. / (i+1))
        # Get new state and reward from environment
        sprime, reward, done, info = env.step(a)
        # Update Q-Table with new knowledge
        Q[s, a] = Q[s, a] + alpha * (r + gamma * np.max(Q[sprime, :]) - Q[s, a])
        rAll += reward
        s = sprime
        if done == True:
            break
        rewardsList.append(rAll)

In [8]:
print "Score over time: " +  str(sum(rList)/num_episodes)
print "Final Q-Table Values"
print Q

Score over time: 0.5625
Final Q-Table Values
[[  1.59598640e-01   1.76867872e-02   1.53506889e-02   1.58404103e-02]
 [  6.28693462e-04   3.62018234e-03   2.54869079e-03   1.47798279e-01]
 [  2.99186428e-03   2.48337779e-03   2.46187372e-03   2.38263743e-01]
 [  9.62295821e-04   8.94648050e-04   2.32334161e-03   8.47611637e-02]
 [  1.62679850e-01   3.36581467e-03   0.00000000e+00   3.19434265e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.49438813e-01   3.19699316e-05   1.22139050e-04   2.87185626e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.26831948e-03   6.76297273e-03   7.71637220e-03   1.22685603e-01]
 [  4.14003269e-04   3.37345201e-01   2.14859481e-03   0.00000000e+00]
 [  5.87458741e-01   2.01174262e-03   5.03528303e-04   4.25338158e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.12801720e-02   0.00000000e